### ISSUE TITLE
用bert4keras做ner任务在选择T5模型，在加载该chinese_t5_pegasus_base预训练模型时报错

### ISSUE THREAD

**Issue by sxk000** [ZhuiyiTechnology/t5-pegasus#17]
苏神你好，首先感谢大佬分享！

我最近在使用bert4keras做实体识别任务，具体脚本用的是：
https://github.com/bojone/bert4keras/blob/master/examples/task_sequence_labeling_ner_crf.py

python3.6.9
tensorflow-gpu 1.14.0
keras 2.3.1
bert4keras 0.10.7

想尝试通过该脚本用t5模型，但是在加载预训练模型chinese_t5_pegasus_base是报如下错误：

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Traceback (most recent call last):
  File "task_sequence_labeling_ner_crf_conlleval.py", line 155, in <module>
    model = build_transformer_model(config_path, checkpoint_path, model=is_albert)
  File "/big_disk/ner_2/bert4keras/models.py", line 2451, in build_transformer_model
    transformer.load_weights_from_checkpoint(checkpoint_path)
  File "/big_disk/ner_2/bert4keras/models.py", line 305, in load_weights_from_checkpoint
    raise e
  File "/big_disk/ner_2/bert4keras/models.py", line 299, in load_weights_from_checkpoint
    values.append(self.load_variable(checkpoint, v))
  File "/big_disk/ner_2/bert4keras/models.py", line 1763, in load_variable
    variable = super(T5_Base, self).load_variable(checkpoint, name)
  File "/big_disk/ner_2/bert4keras/models.py", line 270, in load_variable
    return tf.train.load_variable(checkpoint, name)
  File "/big_disk/venv36/lib/python3.6/site-packages/tensorflow/python/training/checkpoint_utils.py", line 84, in load_variable
    return reader.get_tensor(name)
  File "/big_disk/venv36/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 678, in get_tensor
    return CheckpointReader_GetTensor(self, compat.as_bytes(tensor_str))
tensorflow.python.framework.errors_impl.NotFoundError: Key encoder/final_layer_norm/scale not found in checkpoint

请问可以用该脚本使用t5模型做实体识别任务吗？应该如何解决加载预训练模型chinese_t5_pegasus_base出现的错误呢？

再次感谢大佬！

**Comment by KyrieIrving24** [comment]
请问怎么用这个模型做其他任务呢
